services:

  ollama-auth:
    image: ghcr.io/g1ibby/ollama-auth:latest
    container_name: ollama-auth
    ports:
      - "11435:80"
    environment:
      - OLLAMA_API_KEY=bb80cad2-c418-4eb4-a483-575f163e39d1
